server:
  port: 8030
spring:
  application:
    name: config-server
  zipkin:
    base-url: http://localhost:9411
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/hekun1997/springCloudConfig
          search-paths: /

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
